ALTER TABLE "payments"
  ALTER COLUMN "paid_at"   SET DATA TYPE TIMESTAMP(3),
  ALTER COLUMN "failed_at" SET DATA TYPE TIMESTAMP(3),
  ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
  ALTER COLUMN "updated_at" DROP DEFAULT,
  ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);
